
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABRE_COLCHETE ABRE_PARENTESE ATE ATRIBUICAO DIFERENTE DIVISAO DOIS_PONTOS ENTAO ESCREVA E_LOGICO FECHA_COLCHETE FECHA_PARENTESE FIM FLUTUANTE ID IGUAL INTEIRO LEIA MAIOR MAIOR_IGUAL MAIS MENOR MENOR_IGUAL MENOS MULTIPLICACAO NEGACAO NOTACAO_CIENTIFICA OU_LOGICO REPITA RETORNA SE SENAO VIRGULAexpression : expression MAIS termexpression : expression MENOS termexpression : termterm : term MULTIPLICACAO factorterm : term DIVISAO factorterm : factorfactor : INTEIROfactor : ABRE_PARENTESE expression FECHA_PARENTESE'
    
_lr_action_items = {'INTEIRO':([0,5,6,7,8,9,],[4,4,4,4,4,4,]),'ABRE_PARENTESE':([0,5,6,7,8,9,],[5,5,5,5,5,5,]),'$end':([1,2,3,4,11,12,13,14,15,],[0,-3,-6,-7,-1,-2,-4,-5,-8,]),'MAIS':([1,2,3,4,10,11,12,13,14,15,],[6,-3,-6,-7,6,-1,-2,-4,-5,-8,]),'MENOS':([1,2,3,4,10,11,12,13,14,15,],[7,-3,-6,-7,7,-1,-2,-4,-5,-8,]),'FECHA_PARENTESE':([2,3,4,10,11,12,13,14,15,],[-3,-6,-7,15,-1,-2,-4,-5,-8,]),'MULTIPLICACAO':([2,3,4,11,12,13,14,15,],[8,-6,-7,8,8,-4,-5,-8,]),'DIVISAO':([2,3,4,11,12,13,14,15,],[9,-6,-7,9,9,-4,-5,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,5,],[1,10,]),'term':([0,5,6,7,],[2,2,11,12,]),'factor':([0,5,6,7,8,9,],[3,3,3,3,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression MAIS term','expression',3,'p_expression_plus','calc.py',13),
  ('expression -> expression MENOS term','expression',3,'p_expression_minus','calc.py',17),
  ('expression -> term','expression',1,'p_expression_term','calc.py',21),
  ('term -> term MULTIPLICACAO factor','term',3,'p_term_times','calc.py',25),
  ('term -> term DIVISAO factor','term',3,'p_term_div','calc.py',29),
  ('term -> factor','term',1,'p_term_factor','calc.py',33),
  ('factor -> INTEIRO','factor',1,'p_factor_num','calc.py',37),
  ('factor -> ABRE_PARENTESE expression FECHA_PARENTESE','factor',3,'p_factor_expr','calc.py',41),
]
